"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";

export default function ShipmentWorkspace({ params }: { params: { id: string } }) {
  const [job, setJob] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { api.get(`/api/operations/shipments/${params.id}`).then(setJob).catch(e => setError(e.message)); }, [params.id]);
  if (error) return <div className="card p-4 text-red-600">{error}</div>;
  if (!job) return <div className="text-slate-500">Loading shipment workspace…</div>;
  const facts = job.canonical_facts || {};
  return <div className="space-y-6 max-w-[1160px] mx-auto"><Link href="/shipments" className="text-sm font-semibold text-cyan-700">← Shipments</Link><div className="card p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold tracking-wider text-cyan-700">{job.job_code}</p><h1 className="text-3xl font-bold text-slate-900 mt-1">{facts.pol || "Origin"} → {facts.pod || "Destination"}</h1><p className="text-sm text-slate-500 capitalize mt-1">{job.transport_mode} · {job.status}</p></div><div className="text-right"><div className={job.exception_count ? "text-red-600 font-bold" : "text-emerald-600 font-bold"}>{job.exception_count} open exceptions</div><div className="text-xs text-slate-400 mt-1">Evidence-preserving workspace</div></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6">{[["Booking", facts.booking_number], ["BL", facts.bl_number], ["Container", facts.container_number], ["ETD", facts.etd], ["ETA", facts.eta], ["Consignee", facts.consignee], ["Weight", facts.gross_weight], ["PO", facts.po_number]].map(([label, value]) => <div key={String(label)} className="bg-slate-50 rounded-xl p-3"><div className="text-xs text-slate-400">{label}</div><div className="text-sm font-semibold text-slate-800 mt-1">{value || "—"}</div></div>)}</div></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Timeline">{job.events.map((e: any) => <div key={e.id} className="border-l-2 border-cyan-200 pl-3 py-2"><div className="font-medium text-slate-800 text-sm">{e.title}</div><div className="text-xs text-slate-400">{e.event_type.replaceAll("_", " ")} · {new Date(e.occurred_at).toLocaleString()}</div></div>)}</Panel><Panel title="Exceptions">{job.exceptions.map((e: any) => <div key={e.id} className="p-3 bg-red-50 border border-red-100 rounded-lg mb-2"><div className="font-semibold text-red-800 text-sm">{e.title}</div><div className="text-xs text-red-700 mt-1">{e.description}</div></div>)}{!job.exceptions.length && <div className="text-sm text-slate-400">No open exceptions.</div>}</Panel><Panel title="Documents">{job.documents.map((d: any) => <div key={d.id} className="flex justify-between py-2 border-b border-slate-100 text-sm"><span className="text-slate-700">{d.filename}</span><span className="text-slate-400">{d.document_type.replaceAll("_", " ")}</span></div>)}</Panel><Panel title="Communication">{job.communication.map((e: any) => <div key={e.id} className="py-2 border-b border-slate-100"><div className="font-medium text-sm text-slate-700">{e.subject || "(no subject)"}</div><div className="text-xs text-slate-400">{e.sender} · {e.status}</div></div>)}</Panel><Panel title="Tasks">{job.tasks.map((t: any) => <div key={t.id} className="py-2 text-sm"><div className="font-medium text-slate-700">{t.title}</div><div className="text-xs text-slate-400">{t.state} {t.owner ? `· ${t.owner}` : ""}</div></div>)}</Panel><Panel title="Evidence observations">{job.observations.map((o: any) => <div key={o.id} className="py-2 border-b border-slate-100 text-sm"><span className="font-medium text-slate-700">{o.field}</span>: {String(o.value)}<div className="text-xs text-slate-400">{o.evidence_text} · {Math.round(o.confidence * 100)}% confidence</div></div>)}</Panel></div></div>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="card p-5"><h2 className="font-semibold text-slate-900 mb-3">{title}</h2>{children}</section>; }
